config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :notes
end

app/models/note.rb
class Note < ApplicationRecord
  has_rich_text :body
  belongs_to :user

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[show edit update destroy]

  def index
    @notes = Note.where(user_id: current_user)
  end

  def show
  end

  def new
    @note = Note.new
  end

  def edit
  end

  def create
    @note = Note.new(note_params)
    @note.user = current_user
    if @note.save
      flash[:success] = 'New note created'
      redirect_to notes_path
    else
      flash[:danger] = 'Your note was note created'
      render 'new'
    end
  end

  def update
    if @note.update(note_params)
      flash[:success] = 'Note was successfully updated.'
      redirect_to @note
    else
      flash[:danger] = 'Your note was successfully updated'
      render 'new'
    end
  end

  def destroy
    @note.destroy
    flash[:success] = 'Your note was deleted'
    redirect_to notes_path
  end

  private

  def set_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:title, :body)
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_with(model: note, local: true) do |form| %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.rich_text_area :body, class: 'form-control' %>
  </div>

  <div class="form-group">
    <% if @note %>
      <div class="float-right">
        <%= link_to 'Delete note', note, method: :delete, class: "btn btn-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if @note %>
      <%= link_to "Cancel", notes_path, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", notes_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/notes/_note.html.erb
<div class="row mx-auto w-75 mt-5">
  <% if @notes %>
    <h1>Notes</h1>
  <% end %>

  <div>
    <%= link_to 'Add new Note', new_note_path, class: 'btn btn-primary ml-5' %>
  </div>

  <div class="mx-auto mt-5 w-100">
    <div class="table-responsive">
      <table class="table table-bordered table-hover">
        <thead>
        <tr>
          <th width="25%">Title</th>
          <th width="60%">Description</th>
          <th width="15%">Actions</th>
        </tr>
        </thead>

        <tbody>
        <% @notes.each do |note| %>
          <tr>
            <td>
              <% if note.title.empty? %>
                <%= truncate(strip_tags(note.body.to_s), length: 30) %>
              <% else %>
                <%= link_to note.title, note_path(note) %>
              <% end %>
            </td>
            <td><%= truncate(strip_tags(note.body.to_s), length: 100) %></td>
            <td>
              <%= link_to edit_note_path(note) do %>
                <%= fa_icon 'edit', class: "mx-2", style: "color: green" %>
              <% end %>
              <%= link_to note_path(note), method: :delete, data: { confirm: 'Are you sure?' } do %>
                <%= fa_icon 'trash', style: "color: red" %>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/notes/delete.html.erb
<h1>Notes#delete</h1>
<p>Find me in app/views/notes/delete.html.erb</p>

app/views/notes/edit.html.erb
<%= provide(:title, 'Edit Note') %>

<%= render 'form', note: @note %>

app/views/notes/index.html.erb
<%= provide(:title, 'All Notes') %>

<%= render 'notes/note' %>

app/views/notes/new.html.erb
<%= provide(:title, 'Create New Note') %>

<h1>New post</h1>

<%= render 'form', note: @note %>

app/views/notes/show.html.erb
<%= provide(:title, 'Your Note') %>

<div class="row mx-auto w-50 mt-5">
  <h2><%= @note.title %></h2>
</div>

<div class="row mx-auto w-50">
  <small>Created by <%= current_user.name %>, <%= local_date(@note.created_at) %></small>
</div>

<div class="row mx-auto w-50 mt-2 mb-5">
  <p><%= @note.body %></p>
</div>

<div class="row mx-auto w-50">
  <%= link_to notes_path, class: 'btn btn-success mr-3' do %>
    All Posts
  <% end %>
  <%= link_to edit_note_path(@note), class: 'btn btn-primary mr-3' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit Post
  <% end %>
  <%= link_to edit_note_path(@note), class: 'btn btn-danger' do %>
    Delete Post
  <% end %>
</div>