config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :notes
end

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="text-center font-weight-bold alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer" style="margin-top: 2rem">
    <div class="container justify-content-center text-light">
      &copy; <%= Time.now.year %><a href="https://eclecticsaddlebag.com">&nbsp; EclecticCoding</a>&nbsp; - Designed by&nbsp;
      <a href="https://twitter.comEclecticCoding"> Chuck Smith</a>
    </div>
</footer>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <%= link_to 'Notes App', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto align-items-center">
        <% if logged_in? %>
        <li class="nav-item">
          <%= link_to 'User Dashboard', user_path(current_user), class: "nav-link" %>
        </li>
          <div class="mx-3 nav-link">
            <%= link_to 'Log out', logout_path, method: :delete, class: "btn btn-primary btn-sm" %>
          </div>
        <% else %>
          <li><%= link_to 'Log in', login_path, class: 'btn btn-primary btn-sm' %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>